package solvd.enums;

public enum DocumentType {
  // CIVIL_COMMERCIAL_LAW
  BREACH_CONTRACT,
  TRAFFIC_ACCIDENT,
  REAL_ESTATE,
  LEASING,
  NACIONALITY,
  EVICTION,
  USUCAPTION,

  // FAMILY_LAW
  DIVORCE,
  SUCESION,
  DOMESTIC_VIOLENCE,
  FILIATION,
  FOOD_TENURE_VISITATION_REGIME,
  ADOPTION,

  // LABOR_LAW
  LABOR_DISMISSAL,
  LABOR_ACCIDENT,
  LABOR_PROTECTION,
  WAGE_DIFFERENCE,

  // PENAL_LAW
  FRAUD,
  THEFT,
  ROBBERY,
  ATTEMPTED_HOMICIDE,
  HOMICIDE,
  CAPITAL_BLOCKADE,
}
