package org.solvd.enums;

public enum DocumentType {
  CIVIL_COMMERCIAL_LAW_BREACH_CONTRACT,
  CIVIL_COMMERCIAL_LAW_TRAFFIC_ACCIDENT,
  CIVIL_COMMERCIAL_LAW_REAL_ESTATE,
  CIVIL_COMMERCIAL_LAW_LEASING,
  CIVIL_COMMERCIAL_LAW_NACIONALITY,
  CIVIL_COMMERCIAL_LAW_EVICTION,
  CIVIL_COMMERCIAL_LAW_USUCAPTION,

  FAMILY_LAW_DIVORCE,
  FAMILY_LAW_SUCESION,
  FAMILY_LAW_DOMESTIC_VIOLENCE,
  FAMILY_LAW_FILIATION,
  FAMILY_LAW_FOOD_TENURE_VISITATION_REGIME,
  FAMILY_LAW_ADOPTION,

  LABOR_LAW__DISMISSAL,
  LABOR_LAW__ACCIDENT,
  LABOR_LAW__PROTECTION,
  LABOR_LAW_WAGE_DIFFERENCE,

  PENAL_LAW_FRAUD,
  PENAL_LAW_THEFT,
  PENAL_LAW_ROBBERY,
  PENAL_LAW_ATTEMPTED_HOMICIDE,
  PENAL_LAW_HOMICIDE,
  PENAL_LAW_CAPITAL_BLOCKADE,
}
